Travis: Add a crude check for aborted tests
If functional tests execute a code path which calls exitProcess() the
JVM running the tests is terminated, shadowing any upcoming failing
tests. Fail CI builds if such a case is detected by checking that the
line following

    [...] > GradleLoggingSubprojectTest.analyzer produces ABCD files
            for all .gradle files STARTED

does not start with ":" like in

    :analyzer:testPicked up _JAVA_OPTIONS: -Xmx2048m -Xms512m

Also see the somewhat related Gradle issue at

    https://github.com/gradle/gradle/issues/3610

to remedy the situation.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -23,7 +23,11 @@ script:
       exit 1;
     fi
   - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then
-      ./gradlew -DexcludeTags=Expensive check;
+      ./gradlew -DexcludeTags=Expensive check | tee log.txt;
     else
-      ./gradlew check;
+      ./gradlew check | tee log.txt;
+    fi
+  - if grep -A1 ".+Test.+STARTED$" log.txt | grep -q "^:"; then
+      echo "Some tests seemingly have been aborted.";
+      exit 1;
     fi
